//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarInsAppAssmtP_340.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string YearOfCar { get; set; }
        public string MakeOfCar { get; set; }
        public string ModelOfCar { get; set; }
        public string Dui { get; set; }
        public string SpeedingTickets { get; set; }
        public string Coverage { get; set; }
        public Nullable<int> Quote { get; set; }
    }
}
